---

- name: install libvirt
  hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:
  - name: install libvirt virtualisation group
    dnf: name="@Virtualization" state=present
    tags: packages

  - name: install qemu-img
    dnf: name="qemu-img" state=present
    tags: packages

  - name: install virt-install
    tags: packages
    dnf: name="virt-install" state=present

  tags:  
  - libvirt
  - prereqs

- name: prepare server for kickstart
  hosts: localhost
  connection: local
  become: true
  become_user: root

  vars:
    centos_url: https://www.mirrorservice.org/sites/mirror.centos.org/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso
  
  tasks:
  - name: install apache httpd
    dnf: name=httpd state=present
    tags: 
    - packages
    - apache

  - name: configure the apache service
    service: name=httpd state=started enabled=yes
    tags: 
    - services
    - apache

  - name: permit http traffic
    firewalld: service=http permanent=true state=enabled immediate=true zone=FedoraWorkstation
    tags: 
    - firewall

  - name: create a kickstart file
    copy: src=files/el7.ks dest=/var/www/html/el7.ks
    tags:
    - content
    - apache

  - name: copy boot media
    copy: src=files/CentOS-7-x86_64-Minimal-1511.iso dest=/tmp/CentOS-7-x86_64-Minimal-1511.iso
    tags:
    - content
    - iso

  # - name: download installation media
  #  get_url: url={{ centos_url }} dest=/tmp/
  #  tags: getmedia

- name: create virtual machines
  hosts: localhost
  connection: local
  become: true
  become_user: root

  vars:
    vms:
    - centos01.example.com
    # - centos02.example.com

  tasks:
  - name: create the virtual machine(s)
    # command: virt-install --name {{ item }} --memory 2048 --disk size=8,pool=images --location /tmp/CentOS-7-x86_64-Minimal-1511.iso --graphics none --extra-args 'console=ttyS0,115200 serial ks=http://192.168.122.1/el7.ks' --os-type linux
    command: virt-install --name {{ item }} --memory 2048 --disk size=8,pool=images --location /tmp/CentOS-7-x86_64-Minimal-1511.iso --graphics none --extra-args 'console=ttyS0,115200 serial ks=http://{{ ansible_virbr0.ipv4.address }}/el7.ks' --os-type linux
    with_items: "{{vms}}"
    tags: vmcreate

  # - name: wait for ssh to start
  #   wait_for: 
  #     port: 22 
  #     host: "{{ item.public_ip }}"
  #     timeout: 300
  #   with_items: result.tagged_instances


# - name: install virtual machines
#   hosts: localhost
#   connection: local
#   tasks:
# 
# vim:sw=2:ts=2:et:ai
