---

- name: restart virtual machine(s)
  hosts: all
  connection: local
  become: true
  become_user: root

  tasks:

  - name: stop the virtual machine(s)
    command: virsh destroy {{ inventory_hostname }}
    delegate_to: localhost
    ignore_errors: true

  - name: grab vm mac address(es)
    shell: virsh dumpxml {{ inventory_hostname }} | awk -F\' '/mac address/ { print $2 }' | head -1
    register: mac_address
    delegate_to: localhost

  - name: remove static dhcp mapping(s)
    command: virsh net-update default delete ip-dhcp-host "<host mac='{{ mac_address.stdout }}' name='{{ inventory_hostname_short }}' ip='{{ ansible_host }}' />" --live --config
    delegate_to: localhost
    ignore_errors: true

  - name: destroy the default network
    command: virsh net-destroy default
    delegate_to: localhost

  - name: recreate the default network
    command: virsh net-start default
    delegate_to: localhost

  - name: configure static dhcp mapping(s)
    command: virsh net-update default add ip-dhcp-host "<host mac='{{ mac_address.stdout }}' name='{{ inventory_hostname_short }}' ip='{{ ansible_host }}' />" --live --config
    delegate_to: localhost

  - name: start the virtual machine(s)
    command: virsh start {{ inventory_hostname }}
    delegate_to: localhost

# vim:sw=2:ts=2:et:ai
