---

- name: destroy virtual machine(s)
  hosts: all
  connection: local
  become: true
  become_user: root

  tasks:

  - name: stop the virtual machine
    command: virsh destroy {{ inventory_hostname }}
    delegate_to: localhost
    ignore_errors: true

  - name: grab vm mac addresses
    shell: virsh dumpxml {{ inventory_hostname }} | awk -F\' '/mac address/ { print $2 }'
    register: mac_address
    ignore_errors: true

  - name: check if mac-to-ip mapping exists
    command: grep -q {{ mac_address.stdout }} /var/lib/libvirt/dnsmasq/default.hostsfile
    register: mac_exists
    ignore_errors: true

  - name: remove static dhcp mapping
    command: virsh net-update default delete ip-dhcp-host "<host mac='{{ mac_address.stdout }}' name='{{ inventory_hostname }}' ip='{{ ansible_host }}' />" --live --config
    delegate_to: localhost
    ignore_errors: true

  - name: delete the virtual machine
    command: virsh undefine {{ inventory_hostname }}
    delegate_to: localhost
    ignore_errors: true

  - name: remove the virtual machine image
    file: 
      path: /var/lib/libvirt/images/{{ inventory_hostname }}.qcow2
      state: absent
    ignore_errors: true

# vim:sw=2:ts=2:et:ai
