---

- name: delete virtual machine(s)
  hosts: dev:&dbs
  connection: local
  become: true
  become_user: root

  tasks:

  - name: shutdown the virtual machine(s)
    command: virsh shutdown {{ item }}
    with_items: "{{ inventory_hostname }}"
    delegate_to: localhost
    ignore_errors: yes

  - name: delete the virtual machine(s)
    command: virsh undefine {{ item }}
    with_items: "{{ inventory_hostname }}"
    delegate_to: localhost

  - name: remove the virtual machine disk(s)
    command: rm -f /var/lib/libvirt/images/{{ item }}.qcow2
    with_items: "{{ inventory_hostname }}"
    delegate_to: localhost

# vim:sw=2:ts=2:et:ai
