---

- name: install libvirt
  hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:
  - name: install libvirt virtualisation group
    dnf: name="@Virtualization" state=present
    tags: packages

  - name: install virt-install
    tags: packages
    dnf: name="virt-install" state=present

  tags:  
  - libvirt
  - prereqs

# vim:sw=2:ts=2:et:ai
