---

- name: create virtual machine(s)
  hosts: all
  connection: local
  become: true
  become_user: root

  tasks:

  - name: install the virtual machine(s)
    command: virt-install 
      --name {{ inventory_hostname }} 
      --memory 2048 
      --disk size=16,pool=images 
      --location files/CentOS-7-x86_64-Minimal-1511.iso 
      --graphics none 
      --extra-args 'console=ttyS0,115200 serial ks=http://{{ ansible_virbr0.ipv4.address }}/el7.ks' 
      --os-type linux
      --network network=default,model=virtio
      --network network=default,model=virtio
      --network network=default,model=virtio
      --os-variant rhel7
      creates=/var/lib/libvirt/images/{{ inventory_hostname }}.qcow2
    delegate_to: localhost
    register: vm_install

  - name: wait for virt-install(s) to complete
    virt: 
      name={{ inventory_hostname }}
      command=status
    register: vm_poll
    until: vm_poll.status == 'shutdown'
    retries: 120
    delay: 30
    delegate_to: localhost
    when: vm_install|changed

  - name: grab the first vm mac address(es)
    shell: virsh dumpxml {{ inventory_hostname }} | awk -F\' '/mac address/ { print $2 }' | head -1
    register: mac_address
    when: vm_install|changed

  - name: configure static dhcp mapping(s)
    command: virsh net-update default add ip-dhcp-host "<host mac='{{ mac_address.stdout }}' name='{{ inventory_hostname_short }}' ip='{{ ansible_host }}' />" --live --config
    delegate_to: localhost
    when: vm_install|changed

  - name: start the virtual machine(s)
    command: virsh start {{ inventory_hostname }}
    delegate_to: localhost
    when: vm_install|changed

  - name: add additional disk to the vm(s)
    command: qemu-img create -f raw /var/lib/libvirt/images/{{ inventory_hostname }}-1.qcow2 1G
      creates=/var/lib/libvirt/images/{{ inventory_hostname }}-1.qcow2
    register: disk_add

  - name: attach additional disk to the vm(s)
    command: virsh attach-disk {{ inventory_hostname }} --source /var/lib/libvirt/images/{{ inventory_hostname }}-1.qcow2 --target vdb --persistent
    when: disk_add|changed

  # vars:
  # - {{ play_hosts }}
  # - {{ inventory_hostname }}
  # - {{ hostvars }}
  # - {{ mac_address }}
  # - {{ mac_exists }}
  #
  # - debug: 
  #     var: hostvars

# vim:sw=2:ts=2:et:ai
