---

- name: test variable behaviour
  hosts: vms
  connection: local
  become: true
  become_user: root

  tasks:

  - name: grab mac addresses
    shell: virsh dumpxml {{ item }} | awk -F\' '/mac address/ { print $2 }'
    register: mac_address
    with_items: "{{ inventory_hostname }}"

  # - name: configure static dhcp mapping
  #   command: virsh 
  #     net-update default 
  #     add ip-dhcp-host
  #     "<host mac='{{ item.stdout }}' name='{{ item.item }}' ip='{{ hostvars[{{ item.item }}][inventory_hostname] }}' />"
  #     --live --config
  #   with_items: "{{ mac_address.results }}"

  - debug: msg="item={{ item }}"
    with_items: "{{ mac_address.results }}"

  - debug: msg="ip={{ hostvars[inventory_hostname]['ansible_host'] }}"
    with_items: "{{ mac_address.results }}"

  # - name: start the virtual machine(s)
  #   command: virsh start {{ item }}
  #   with_items: "{{ inventory_hostname }}"
  #   delegate_to: localhost

# vim:sw=2:ts=2:et:ai
